### ISSUE TITLE
问下为啥about 页面的avatar 显示不生效？

### ISSUE THREAD

**Issue by lovedva** [weekdaycare/weekdaycare.github.io#120]
设置的avatar在主页和博客生效，在about不生效，还是显示的照相机，另wiki的左上头像在哪里设置啊

**Comment by weekdaycare** [comment]
不知道你说的about是什么样的？wiki的头像是在 `blog/source/_data/wiki/xxx.yml` 中设置项目的icon
```yaml
name: Stellar
title: Stellar - 每个人的独立博客
subtitle: '每个人的独立博客 | Designed by xaoxuu'
tags: 博客主题
icon: /assets/wiki/stellar/icon.svg # 这个
cover: /assets/wiki/stellar/icon.svg
```
