### ISSUE TITLE
淦，做核酸时候下雨了

### ISSUE THREAD

**Issue by weekdaycare** [weekdaycare/weekdaycare.github.io#21]
没带伞`˚‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚`

**Comment by Achuan-2** [comment]
大佬，想问问怎么控制近期动态只展示一条的

**Comment by weekdaycare** [comment]
@Achuan-2 `api`后面加上`?per_page=1`就可以啦，比如`https://api.github.com/repos/weekdaycare/weekdaycare.github.io/issues?per_page=1`，更多的可以参考[issue官方文档](https://docs.github.com/en/rest/issues/issues#list-issues-assigned-to-the-authenticated-user)

**Comment by Achuan-2** [comment]
哇，感谢！

**Comment by Achuan-2** [comment]
还有一个问题，还想打扰大佬问问，近期动态这里为啥我有滚动条呢，而你的博客没有
![Snipaste_2022-10-29_10-37-28](https://user-images.githubusercontent.com/60436214/198781954-817a0559-d6fb-41cc-ae4b-eec6e5b76652.png)

**Comment by weekdaycare** [comment]
@Achuan-2 我的博客本来也是有的，问了大佬说是浏览器兼容的问题，你换个设备访问应该就不会出现滚动条，我这里没有滚动条是因为我手动引用了一个滚动条css文件`scrollbar.css`，你可以看到我网站的滚动条都不是默认的

**Comment by weekdaycare** [comment]
@Achuan-2 
<details>
<summary>scrollbar.css</summary>

```css
/* 滚动条 */
::-webkit-scrollbar {
	width: 10px;
	height: 8px;
  }
  
  ::-webkit-scrollbar-track {
	background-color: rgba(200,155,155,0); //最后一位数置0
	border-radius: 2em;
  }
  
  ::-webkit-scrollbar-thumb {
	background-color: #ffc0cb !important;
	background-image: -webkit-linear-gradient(
	  45deg,
	  rgba(255, 255, 255, 0.4) 25%,
	  transparent 25%,
	  transparent 50%,
	  rgba(255, 255, 255, 0.4) 50%,
	  rgba(255, 255, 255, 0.4) 75%,
	  transparent 75%,
	  transparent
	) !important;
	border-radius: 2em;
  }
  
  ::-webkit-scrollbar-corner {
	background-color: transparent;
  }
  
  [data-theme="dark"] ::-webkit-scrollbar-thumb {
	background-color: #1f1f1f !important;
  }
```

</details>
